---
- name: Provision EC2 with Docker and Docker Compose  
  hosts: web
  become: true
  gather_facts: no 

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install Python and pip
      apt:
        name: 
          - python3
          - python3-pip
        state: present
    - name: Ensure Python 3.10 is installed
      raw: |
        sudo apt update
        udo apt install -y python3.10 python3.10-venv python3.10-distutils
        
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose version
      command: docker-compose --version
