version: '3.8'

services:
  flaskapp:
    build: .
    container_name: Flask-WeatherApp
    expose:
      - "5000"
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: Nginx-WeatherApps
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flaskapp
    restart: unless-stopped
