version: '3'
services:
  flask:
    build: .
    container_name: flask_app
    env_file:
      - .env
    expose:
      - "5000"
    volumes:
      - ./logs:/var/log/gunicorn

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask