- name: Configure EC2 for Weather App
  hosts: ec2
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reboot to apply group changes
      reboot:
        msg: "Rebooting to apply docker group changes"
        reboot_timeout: 300

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy Nginx configuration
      copy:
        src: templates/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Restart Nginx

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Amazon CloudWatch agent
      shell: |
        wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        sudo dpkg -i -E ./amazon-cloudwatch-agent.deb
      args:
        creates: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl  

    - name: Configure CloudWatch agent
      copy:
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "logfile": "/var/log/amazon-cloudwatch-agent.log"
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/app/logs/app.log",
                      "log_group_name": "/weather/app/logs",
                      "log_stream_name": "{instance_id}"
                    }
                  ]
                }
              }
            }
          }
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        mode: '0644'
      notify: Restart CloudWatch Logs agent

    - name: Start CloudWatch agent
      service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart CloudWatch Logs agent
      service:
        name: amazon-cloudwatch-agent
        state: restarted